### ISSUE TITLE
find a way to style dom highlighted nodes

### ISSUE THREAD

**Issue by mauricecruz** [mauricecruz/zero-base-themes#44]
Canary has a new feature that highlights dom changes in the elements panel. 

![image](https://cloud.githubusercontent.com/assets/1640686/6097749/fea7d39a-af96-11e4-9d56-2e9216bef5c7.png)

I can override the `.dom-update-highlight` selector by prefixing it with either `::shadow` or `/deep/`. But I can't figure out a way to override the animation.  

It leverages these styles injected into the shadow root:

``` css
@-webkit-keyframes dom-update-highlight-animation {
    from {
        background-color: rgb(158, 54, 153);
        color: white;
    }
    80% {
        background-color: rgb(245, 219, 244);
        color: inherit;
    }
    to {
        background-color: inherit;
    }
}

.dom-update-highlight {
    -webkit-animation: dom-update-highlight-animation 1.4s 1 cubic-bezier(0, 0, 0.2, 1);
    border-radius: 2px;
}
```

It is possible to 'inject' keyframes into shadow dom without using js?
