### ISSUE TITLE
Changing source code font everywhere

### ISSUE THREAD

**Issue by ramgp** [mauricecruz/zero-base-themes#62]
How do we change the font-family for all source code places (console, elements, etc)?

By adding the following to stable.css and/or canary.css, as far as I know, only the prompt line in the console changes the font to the desired one.
```css
body.platform-linux .source-code {
  font-family: Fantasque Sans Mono, dejavu sans mono, monospace;
}
```
Is there a way to target those root shadowed elements with a similar styling?

**Comment by mauricecruz** [comment]
I haven't tried yet, but you can probably try prefixing `::shadow` to the
selector.



- Maurice

**Comment by mauricecruz** [comment]
You'll probably have to pick the right selector group based on your OS, but it'll pretty much change all the source code fonts in devtools

``` css
:host-context(.platform-mac) .monospace,
:host-context(.platform-mac) .source-code,
.platform-mac .monospace,
.platform-mac .source-code {
    font-size: 11px !important;
    font-family: Menlo, monospace;
}

:host-context(.platform-windows) .monospace,
:host-context(.platform-windows) .source-code,
.platform-windows .monospace,
.platform-windows .source-code {
    font-size: 12px !important;
    font-family: Consolas, Lucida Console, monospace;
}

:host-context(.platform-linux) .monospace,
:host-context(.platform-linux) .source-code,
.platform-linux .monospace,
.platform-linux .source-code {
    font-size: 11px !important;
    font-family: dejavu sans mono, monospace;
}

.source-code {
    font-family: monospace;
    font-size: 11px !important;
    white-space: pre-wrap;
}
```

![image](https://cloud.githubusercontent.com/assets/1640686/9422448/d354a34e-4861-11e5-946e-1df318741f48.png)
